#!/usr/bin/env zsh

# If MacOS
if [ $(uname -s) = 'Darwin' ]; then

    # Homebrew, -z string True if the length of string is zero.
    [ -z "$(which brew)" ] &&
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    echo "Updating homebrew"
    brew update

    echo "Installing brew things..."
    ruby -e '
      d = %w(
        tmux ag z wget vim trash m-cli tig htop vim bash zsh elixir rbenv highlight
        git git-extras mas tree fzf fortune coreutils ssh-copy-id
      ) - %x(brew list).split(" ")
      print d.join(" ")
    ' | xargs brew install


    if brew tap-info caskroom/cask | grep -q "Not installed"; then
      echo "Installing brew cask..."
      brew tap caskroom/cask
    fi


    if brew tap-info caskroom/fonts | grep -q "Not installed"; then
      echo "Installing brew fonts..."
      brew tap caskroom/fonts
    fi

    echo "Installing brew cask things..."
    brew cask install qlcolorcode qlstephen qlmarkdown \
      quicklook-json qlprettypatch quicklook-csv \
      betterzipql qlimagesize webpquicklook suspicious-package

    echo "Installing brew cask apps..."
    brew cask install spectacle

    echo "Installing brew cask fonts..."
    brew cask install \
    font-dejavu-sans \
    font-inconsolata \
    font-meslo-lg \
    font-ubuntu \
    font-fira-code \
    font-inconsolata-g-for-powerline \
    font-meslo-lg-for-powerline \
    font-hermit \
    font-input
fi
