#!/usr/bin/env zsh

if [[ `uname` == 'Darwin' ]]; then
  which -s brew
  if [[ $? != 0 ]]; then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew update
    brew install tmux \
    z vim trash \
    m-cli tig htop vim bash zsh \
    elixir rbenv \
    git git-extras mas fzf fortune coreutils\
    ssh-copy-id

    brew tap caskroom/cask
    brew cask install qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv betterzipql qlimagesize webpquicklook suspicious-package
    brew cask install spectacle \
    font-dejavu-sans \
    font-inconsolata \
    font-meslo-lg \
    font-ubuntu \
    font-fira-code \
    font-inconsolata-g-for-powerline \
    font-meslo-lg-for-powerline \
    font-hermit \
    font-input
  fi
fi
