#!/usr/bin/env zsh

pushd home
  for i in .*; do
    [ -e $i ] || continue # for safaty
    if [ -e $HOME/$i ]; then
      mkdir -pv ../bak && mv -v $HOME/$i ../bak/$i
    fi
    ln -sfv $PWD/$i $HOME/$i
  done
popd home

# link zprezto
for i in $PWD/zprezto/runcoms/z*; do
  ln -svf $i $HOME/.${i:t}
done
ln -svf $PWD/zprezto $HOME/.zprezto

pushd ..
  if [ $(uname -s) = 'Darwin' ]; then

    sublimeuser="$HOME/Library/Application Support/Sublime Text 3/Packages/User"
    if [ -d $sublimeuser  ]; then
      echo "Sublime user dir exists backing up..."
      mkdir -pv bak && mv $sublimeuser bak/original-sublime-user
    fi

    echo "Linking Sublime dir..."
    ln -sv $PWD/sublime/User $sublimeuser

    [ ! -e /usr/local/bin/subl ] && ln -svf "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin
  fi

  # vim
  export GIT_SSL_NO_VERIFY=true
  mkdir -p ~/.vim/autoload
  curl --insecure -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim

  # vimrc
  mv -v ~/.vimrc $PWD/bak/.vimrc.old 2> /dev/null
  ln -sf $PWD/home/.vimrc ~/.vimrc

  # nvim
  mkdir -p ~/.config/nvim/autoload
  ln -sf $PWD/home/.vimrc ~/.config/nvim/init.vim
  ln -sf ~/.vim/autoload/plug.vim ~/.config/nvim/autoload/

  vim +PlugInstall +qall
popd ..
